// GENERATED by scripts/build-palette.mjs — do not edit by hand.
// Re-run `node scripts/build-palette.mjs` after updating scripts/eco-raw/.
export interface BlockType {
  id: string;
  name: string;
  color: string; // hex fallback (average color of the texture, or of the icon if untextured)
  texture?: string; // path under /public to a tiling surface texture; optional
  // Path to a distinct top/bottom-face texture for the 'floor' shape, when the
  // block's in-game Floor material genuinely differs from its Cube/side
  // texture (verified per-family via the game's own Material bindings, not
  // assumed — see build-palette.mjs's BLOCKS comment). Falls back to
  // `texture` on every face when omitted, which is correct for every family
  // except Brick so far.
  floorTopTexture?: string;
  // [x, y] UV repeat scale for `texture` on box-rendered faces (Cube, and
  // Floor's side faces), correcting for our plain 0..1 box UVs vs Eco's real
  // Cube mesh, which only ever samples a small crop of the source texture
  // per face. Verified per-material from that real mesh's own baked UV span
  // — not guessed — so this is only present where confirmed; every material
  // without it renders at the original (pre-fix) 1:1 scale, unchanged.
  textureRepeat?: [number, number];
  // When true, the block picker prefers the inventory icon over the surface
  // texture for its preview swatch — for blocks whose extracted texture is a
  // good tileable 3D surface but a poor standalone picture (e.g. Pipes: a
  // plain metal swatch, vs. a clean IronPipeItem-style icon).
  preferIconInPicker?: boolean;
  opacity?: number; // 0-1; 3D-only, e.g. for glass. Defaults to fully opaque (1) when omitted.
}

export const BLOCK_PALETTE: BlockType[] = [
  { id: 'ashlar_basalt', name: 'Ashlar Basalt', color: '#575964', texture: '/textures/blocks/ashlar_basalt.png' },
  { id: 'ashlar_granite', name: 'Ashlar Granite', color: '#79756f', texture: '/textures/blocks/ashlar_granite.png' },
  { id: 'ashlar_gneiss', name: 'Ashlar Gneiss', color: '#5c5245', texture: '/textures/blocks/ashlar_gneiss.png' },
  { id: 'ashlar_limestone', name: 'Ashlar Limestone', color: '#cfcdb8', texture: '/textures/blocks/ashlar_limestone.png' },
  { id: 'ashlar_sandstone', name: 'Ashlar Sandstone', color: '#c27640', texture: '/textures/blocks/ashlar_sandstone.png' },
  { id: 'ashlar_shale', name: 'Ashlar Shale', color: '#393e3f', texture: '/textures/blocks/ashlar_shale.png' },
  { id: 'brick', name: 'Brick', color: '#974327', texture: '/textures/blocks/brick.png', floorTopTexture: '/textures/blocks/brick_floor_top.png', textureRepeat: [0.279, 0.295] },
  { id: 'adobe', name: 'Adobe', color: '#735a34', texture: '/textures/blocks/adobe.png' },
  { id: 'hewn_log', name: 'Hewn Log', color: '#ca9a63', texture: '/textures/blocks/hewn_log.png' },
  { id: 'hardwood_hewn_log', name: 'Hardwood Hewn Log', color: '#b88f66', texture: '/textures/blocks/hardwood_hewn_log.png' },
  { id: 'softwood_hewn_log', name: 'Softwood Hewn Log', color: '#c2aa8f', texture: '/textures/blocks/softwood_hewn_log.png' },
  { id: 'lumber', name: 'Lumber', color: '#e6ccab', texture: '/textures/blocks/lumber.png' },
  { id: 'hardwood_lumber', name: 'Hardwood Lumber', color: '#d1a372', texture: '/textures/blocks/hardwood_lumber.png' },
  { id: 'softwood_lumber', name: 'Softwood Lumber', color: '#e6ccac', texture: '/textures/blocks/softwood_lumber.png' },
  { id: 'composite_lumber', name: 'Composite Lumber', color: '#eacfae', texture: '/textures/blocks/composite_lumber.png' },
  { id: 'composite_lumber_birch', name: 'Composite Birch Lumber', color: '#dcb380', texture: '/textures/blocks/composite_lumber_birch.png' },
  { id: 'composite_lumber_cedar', name: 'Composite Cedar Lumber', color: '#a86838', texture: '/textures/blocks/composite_lumber_cedar.png' },
  { id: 'composite_lumber_ceiba', name: 'Composite Ceiba Lumber', color: '#ab9578', texture: '/textures/blocks/composite_lumber_ceiba.png' },
  { id: 'composite_lumber_fir', name: 'Composite Fir Lumber', color: '#e4ae82', texture: '/textures/blocks/composite_lumber_fir.png' },
  { id: 'composite_lumber_joshua', name: 'Composite Joshua Lumber', color: '#cd9664', texture: '/textures/blocks/composite_lumber_joshua.png' },
  { id: 'composite_lumber_oak', name: 'Composite Oak Lumber', color: '#835c2c', texture: '/textures/blocks/composite_lumber_oak.png' },
  { id: 'composite_lumber_palm', name: 'Composite Palm Lumber', color: '#c66d2e', texture: '/textures/blocks/composite_lumber_palm.png' },
  { id: 'composite_lumber_redwood', name: 'Composite Redwood Lumber', color: '#602f1e', texture: '/textures/blocks/composite_lumber_redwood.png' },
  { id: 'composite_lumber_saguaro', name: 'Composite Saguaro Lumber', color: '#5f471c', texture: '/textures/blocks/composite_lumber_saguaro.png' },
  { id: 'composite_lumber_spruce', name: 'Composite Spruce Lumber', color: '#f3dba7', texture: '/textures/blocks/composite_lumber_spruce.png' },
  { id: 'mortared_stone', name: 'Mortared Stone', color: '#898e9a', texture: '/textures/blocks/mortared_stone.png' },
  { id: 'mortared_granite', name: 'Mortared Granite', color: '#807e7c', texture: '/textures/blocks/mortared_granite.png' },
  { id: 'mortared_limestone', name: 'Mortared Limestone', color: '#c0bba9', texture: '/textures/blocks/mortared_limestone.png' },
  { id: 'mortared_sandstone', name: 'Mortared Sandstone', color: '#c18460', texture: '/textures/blocks/mortared_sandstone.png' },
  { id: 'reinforced_concrete', name: 'Reinforced Concrete', color: '#929592', texture: '/textures/blocks/reinforced_concrete.png' },
  { id: 'flat_steel', name: 'Flat Steel', color: '#a7a8a7', texture: '/textures/blocks/flat_steel.png' },
  { id: 'corrugated_steel', name: 'Corrugated Steel', color: '#4a6280', texture: '/textures/blocks/corrugated_steel.png' },
  { id: 'carpet_cotton', name: 'Cotton Carpet', color: '#a18e46', texture: '/textures/blocks/carpet_cotton.png' },
  { id: 'carpet_nylon', name: 'Nylon Carpet', color: '#6885a1', texture: '/textures/blocks/carpet_nylon.png' },
  { id: 'carpet_wool', name: 'Wool Carpet', color: '#a5936a', texture: '/textures/blocks/carpet_wool.png' },
  { id: 'dirt_road', name: 'Dirt Road', color: '#9b774d', texture: '/textures/blocks/dirt_road.png' },
  { id: 'stone_road', name: 'Stone Road', color: '#697676', texture: '/textures/blocks/stone_road.png' },
  { id: 'asphalt_road', name: 'Asphalt Road', color: '#5e5d5e', texture: '/textures/blocks/asphalt_road.png' },
  { id: 'glass', name: 'Glass', color: '#8fcce6', opacity: 0.5 },
  { id: 'framed_glass', name: 'Framed Glass', color: '#8fcce6', texture: '/textures/blocks/framed_glass.png', opacity: 0.7 },
  { id: 'iron_pipe', name: 'Iron Pipe', color: '#626a76', texture: '/textures/blocks/iron_pipe.png', preferIconInPicker: true },
  { id: 'steel_pipe', name: 'Steel Pipe', color: '#8d9496', texture: '/textures/blocks/steel_pipe.png', preferIconInPicker: true },
  { id: 'copper_pipe', name: 'Copper Pipe', color: '#ac5b31', texture: '/textures/blocks/copper_pipe.png', preferIconInPicker: true },
];

export const DEFAULT_BLOCK_COLOR = '#e05fd0'; // fallback for unknown blockTypeId on import

export function getBlockColor(blockTypeId: string): string {
  return BLOCK_PALETTE.find((b) => b.id === blockTypeId)?.color ?? DEFAULT_BLOCK_COLOR;
}

export function getBlockName(blockTypeId: string): string {
  return BLOCK_PALETTE.find((b) => b.id === blockTypeId)?.name ?? blockTypeId;
}

export function getBlockTexture(blockTypeId: string): string | undefined {
  const texture = BLOCK_PALETTE.find((b) => b.id === blockTypeId)?.texture;
  // Resolve against Vite's base URL so assets load under a GitHub Pages project
  // subpath (e.g. /EcoPlanner/) rather than the domain root.
  return texture ? import.meta.env.BASE_URL + texture.replace(/^\/+/, '') : undefined;
}

export function getBlockIcon(blockTypeId: string): string {
  return `${import.meta.env.BASE_URL}icons/blocks/${blockTypeId}.png`;
}

// undefined unless this block has a genuinely distinct top/bottom-face
// texture for the 'floor' shape — falls back to getBlockTexture() otherwise.
export function getBlockFloorTopTexture(blockTypeId: string): string | undefined {
  const texture = BLOCK_PALETTE.find((b) => b.id === blockTypeId)?.floorTopTexture;
  return texture ? import.meta.env.BASE_URL + texture.replace(/^\/+/, '') : undefined;
}

// [1, 1] (i.e. no change) unless a verified scale exists for this block — see
// BlockType.textureRepeat's doc comment.
export function getBlockTextureRepeat(blockTypeId: string): [number, number] {
  return BLOCK_PALETTE.find((b) => b.id === blockTypeId)?.textureRepeat ?? [1, 1];
}

export function getBlockOpacity(blockTypeId: string): number {
  return BLOCK_PALETTE.find((b) => b.id === blockTypeId)?.opacity ?? 1;
}
